name: "Exemplo de CD"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull matheuslessa/ci-example:latest

      - name: Stop Docker container
        run: docker stop ci-example || true

      - name: Remove Docker container
        run: docker rm ci-example || true

      - name: Run Docker container
        run: docker run -d --name ci-example -p 8080:8080 matheuslessa/ci-example:latest